"""create_models_for_payment_model

Revision ID: fa0dd59114dc
Revises:
Create Date: 2025-04-07 18:02:01.909842

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa0dd59114dc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("tier_id", sa.Uuid(), nullable=False),
        sa.Column("stripe_checkout_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stripe_payment_intent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", "CANCELED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_id"), "payment", ["id"], unique=False)
    op.create_index(op.f("ix_payment_status"), "payment", ["status"], unique=False)
    op.create_index(
        op.f("ix_payment_stripe_checkout_session_id"),
        "payment",
        ["stripe_checkout_session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_stripe_payment_intent_id"),
        "payment",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_subscription_id"), "payment", ["subscription_id"], unique=False
    )
    op.create_index(op.f("ix_payment_tier_id"), "payment", ["tier_id"], unique=False)
    op.create_index(op.f("ix_payment_user_id"), "payment", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_user_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_tier_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_subscription_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_stripe_payment_intent_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_stripe_checkout_session_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_status"), table_name="payment")
    op.drop_index(op.f("ix_payment_id"), table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
